name: Documentation Deployment

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare docs folder
        run: |
          echo "Preparing documentation for deployment..."
          mkdir -p public
          cp -r docs/* public/
          echo "Documentation ready."

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public/

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
