name: Documentation Deployment

on:
  push:
    paths:
      - 'docs/**'
      - '.github/workflows/documentation.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Prepare docs folder
        run: |
          echo "Preparing documentation for deployment..."
          mkdir -p ./_site
          cp -r docs/* ./_site/
          echo "Documentation ready."

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  
    steps:
      - name: Deploy documentation to `gh-pages-docs` branch
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages-docs

